import type { Ticket, TicketPriority, TicketStatus, TicketType } from "@/app/(client)/meus-pedidos/lib/mock-tickets";

export type GestorTicket = Ticket & {
  requesterId?: string;
  requesterName: string;
};

export const gestorTicketsMock: GestorTicket[] = [
  {
    id: "g1",
    code: "TKT-2024-001",
    subject: "Solicitação Novo Cartão - Cliente Lorrys",
    type: "PEDIDO CARTAO" as TicketType,
    requester: "Lorrys Cliente",
    requesterName: "Lorrys",
    requesterRole: "Cliente",
    requesterId: "CL-001",
    priority: "Alta" as TicketPriority,
    status: "EM ANALISE" as TicketStatus,
    createdAt: "2024-05-20",
    requestTypeLabel: "Pedido de Cartão Frota+",
    description: "Solicitação criada pelo gestor para emissão de novo cartão.",
  },
  {
    id: "g2",
    code: "TKT-2024-002",
    subject: "Abastecimento Manual - Emergência",
    type: "ABASTECIMENTO MANUAL" as TicketType,
    requester: "Lorrys Cliente",
    requesterName: "Lorrys",
    requesterRole: "Cliente",
    requesterId: "CL-001",
    priority: "Urgente" as TicketPriority,
    status: "ABERTO" as TicketStatus,
    createdAt: "2024-05-21",
    requestTypeLabel: "Abastecimento Manual",
    description: "Abastecimento fora do fluxo normal.",
    matricula: "LD-22-33-AA",
  },
  {
    id: "g3",
    code: "TKT-2024-003",
    subject: "Carregamento Conta Frota",
    type: "CARREGAMENTO" as TicketType,
    requester: "Carlos Gestor",
    requesterName: "Carlos",
    requesterRole: "Gestor",
    requesterId: "GT-014",
    priority: "Normal" as TicketPriority,
    status: "APROVADO" as TicketStatus,
    createdAt: "2024-05-19",
    requestTypeLabel: "Carregamento",
    description: "Carregamento aprovado para conta frota.",
  },
  {
    id: "g4",
    code: "TKT-2024-004",
    subject: "Erro de Leitura Chip",
    type: "SUPORTE" as TicketType,
    requester: "Lorrys Cliente",
    requesterName: "Lorrys",
    requesterRole: "Cliente",
    requesterId: "CL-001",
    priority: "Normal" as TicketPriority,
    status: "ATRIBUIDO" as TicketStatus,
    createdAt: "2024-05-21",
    requestTypeLabel: "Suporte",
    description: "Cartão com erro de leitura no posto.",
  },
  {
    id: "g5",
    code: "TKT-2024-005",
    subject: "Regularização Abastecimento - Fim de Semana",
    type: "ABASTECIMENTO MANUAL" as TicketType,
    requester: "Maria Santos",
    requesterName: "Maria Santos",
    requesterRole: "Cliente",
    requesterId: "CL-029",
    priority: "Alta" as TicketPriority,
    status: "EM ANALISE" as TicketStatus,
    createdAt: "2024-05-18",
    requestTypeLabel: "Abastecimento Manual",
    description: "Pedido para regularização do abastecimento manual.",
  },
  {
    id: "g6",
    code: "TKT-2024-006",
    subject: "Abastecimento Aprovado - Rotina",
    type: "ABASTECIMENTO MANUAL" as TicketType,
    requester: "Lorrys Cliente",
    requesterName: "Lorrys",
    requesterRole: "Cliente",
    requesterId: "CL-001",
    priority: "Baixa" as TicketPriority,
    status: "APROVADO" as TicketStatus,
    createdAt: "2024-05-10",
    requestTypeLabel: "Abastecimento Manual",
    description: "Abastecimento aprovado para rotina.",
    matricula: "LD-22-33-AA",
  },
];

